// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Datatypes.proto

package ru.chuprikov.search.database.datatypes;

public final class Datatypes {
  private Datatypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PostingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 documentID = 1;
    boolean hasDocumentID();
    long getDocumentID();
    
    // repeated .ru.chuprikov.search.database.datatypes.Posting.Position positions = 2;
    java.util.List<ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position> 
        getPositionsList();
    ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position getPositions(int index);
    int getPositionsCount();
    java.util.List<? extends ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionOrBuilder> 
        getPositionsOrBuilderList();
    ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionOrBuilder getPositionsOrBuilder(
        int index);
  }
  public static final class Posting extends
      com.google.protobuf.GeneratedMessage
      implements PostingOrBuilder {
    // Use Posting.newBuilder() to construct.
    private Posting(Builder builder) {
      super(builder);
    }
    private Posting(boolean noInit) {}
    
    private static final Posting defaultInstance;
    public static Posting getDefaultInstance() {
      return defaultInstance;
    }
    
    public Posting getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.chuprikov.search.database.datatypes.Datatypes.internal_static_ru_chuprikov_search_database_datatypes_Posting_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.chuprikov.search.database.datatypes.Datatypes.internal_static_ru_chuprikov_search_database_datatypes_Posting_fieldAccessorTable;
    }
    
    public enum PositionType
        implements com.google.protobuf.ProtocolMessageEnum {
      TITLE(0, 1),
      CONDITION(1, 2),
      INPUT_SPEC(2, 3),
      OUTPUT_SPEC(3, 4),
      ;
      
      public static final int TITLE_VALUE = 1;
      public static final int CONDITION_VALUE = 2;
      public static final int INPUT_SPEC_VALUE = 3;
      public static final int OUTPUT_SPEC_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static PositionType valueOf(int value) {
        switch (value) {
          case 1: return TITLE;
          case 2: return CONDITION;
          case 3: return INPUT_SPEC;
          case 4: return OUTPUT_SPEC;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<PositionType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PositionType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PositionType>() {
              public PositionType findValueByNumber(int number) {
                return PositionType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ru.chuprikov.search.database.datatypes.Datatypes.Posting.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final PositionType[] VALUES = {
        TITLE, CONDITION, INPUT_SPEC, OUTPUT_SPEC, 
      };
      
      public static PositionType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private PositionType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:ru.chuprikov.search.database.datatypes.Posting.PositionType)
    }
    
    public interface PositionOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required .ru.chuprikov.search.database.datatypes.Posting.PositionType type = 1;
      boolean hasType();
      ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType getType();
      
      // required uint32 index = 2;
      boolean hasIndex();
      int getIndex();
    }
    public static final class Position extends
        com.google.protobuf.GeneratedMessage
        implements PositionOrBuilder {
      // Use Position.newBuilder() to construct.
      private Position(Builder builder) {
        super(builder);
      }
      private Position(boolean noInit) {}
      
      private static final Position defaultInstance;
      public static Position getDefaultInstance() {
        return defaultInstance;
      }
      
      public Position getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.chuprikov.search.database.datatypes.Datatypes.internal_static_ru_chuprikov_search_database_datatypes_Posting_Position_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.chuprikov.search.database.datatypes.Datatypes.internal_static_ru_chuprikov_search_database_datatypes_Posting_Position_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required .ru.chuprikov.search.database.datatypes.Posting.PositionType type = 1;
      public static final int TYPE_FIELD_NUMBER = 1;
      private ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType type_;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType getType() {
        return type_;
      }
      
      // required uint32 index = 2;
      public static final int INDEX_FIELD_NUMBER = 2;
      private int index_;
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getIndex() {
        return index_;
      }
      
      private void initFields() {
        type_ = ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType.TITLE;
        index_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasIndex()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, type_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt32(2, index_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, index_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      @java.lang.Override
      protected Object writeReplace() throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ru.chuprikov.search.database.datatypes.Datatypes.internal_static_ru_chuprikov_search_database_datatypes_Posting_Position_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ru.chuprikov.search.database.datatypes.Datatypes.internal_static_ru_chuprikov_search_database_datatypes_Posting_Position_fieldAccessorTable;
        }
        
        // Construct using ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          type_ = ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType.TITLE;
          bitField0_ = (bitField0_ & ~0x00000001);
          index_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.getDescriptor();
        }
        
        public ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position getDefaultInstanceForType() {
          return ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.getDefaultInstance();
        }
        
        public ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position build() {
          ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position buildPartial() {
          ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position result = new ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.index_ = index_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position) {
            return mergeFrom((ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position other) {
          if (other == ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.getDefaultInstance()) return this;
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasIndex()) {
            setIndex(other.getIndex());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasType()) {
            
            return false;
          }
          if (!hasIndex()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType value = ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  type_ = value;
                }
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                index_ = input.readUInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required .ru.chuprikov.search.database.datatypes.Posting.PositionType type = 1;
        private ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType type_ = ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType.TITLE;
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType getType() {
          return type_;
        }
        public Builder setType(ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionType.TITLE;
          onChanged();
          return this;
        }
        
        // required uint32 index = 2;
        private int index_ ;
        public boolean hasIndex() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getIndex() {
          return index_;
        }
        public Builder setIndex(int value) {
          bitField0_ |= 0x00000002;
          index_ = value;
          onChanged();
          return this;
        }
        public Builder clearIndex() {
          bitField0_ = (bitField0_ & ~0x00000002);
          index_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:ru.chuprikov.search.database.datatypes.Posting.Position)
      }
      
      static {
        defaultInstance = new Position(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:ru.chuprikov.search.database.datatypes.Posting.Position)
    }
    
    private int bitField0_;
    // required uint64 documentID = 1;
    public static final int DOCUMENTID_FIELD_NUMBER = 1;
    private long documentID_;
    public boolean hasDocumentID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getDocumentID() {
      return documentID_;
    }
    
    // repeated .ru.chuprikov.search.database.datatypes.Posting.Position positions = 2;
    public static final int POSITIONS_FIELD_NUMBER = 2;
    private java.util.List<ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position> positions_;
    public java.util.List<ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position> getPositionsList() {
      return positions_;
    }
    public java.util.List<? extends ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionOrBuilder> 
        getPositionsOrBuilderList() {
      return positions_;
    }
    public int getPositionsCount() {
      return positions_.size();
    }
    public ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position getPositions(int index) {
      return positions_.get(index);
    }
    public ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionOrBuilder getPositionsOrBuilder(
        int index) {
      return positions_.get(index);
    }
    
    private void initFields() {
      documentID_ = 0L;
      positions_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDocumentID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPositionsCount(); i++) {
        if (!getPositions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, documentID_);
      }
      for (int i = 0; i < positions_.size(); i++) {
        output.writeMessage(2, positions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, documentID_);
      }
      for (int i = 0; i < positions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, positions_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ru.chuprikov.search.database.datatypes.Datatypes.Posting parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ru.chuprikov.search.database.datatypes.Datatypes.Posting parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ru.chuprikov.search.database.datatypes.Datatypes.Posting parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ru.chuprikov.search.database.datatypes.Datatypes.Posting parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ru.chuprikov.search.database.datatypes.Datatypes.Posting parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ru.chuprikov.search.database.datatypes.Datatypes.Posting parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ru.chuprikov.search.database.datatypes.Datatypes.Posting parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ru.chuprikov.search.database.datatypes.Datatypes.Posting parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ru.chuprikov.search.database.datatypes.Datatypes.Posting parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ru.chuprikov.search.database.datatypes.Datatypes.Posting parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.chuprikov.search.database.datatypes.Datatypes.Posting prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ru.chuprikov.search.database.datatypes.Datatypes.PostingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.chuprikov.search.database.datatypes.Datatypes.internal_static_ru_chuprikov_search_database_datatypes_Posting_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.chuprikov.search.database.datatypes.Datatypes.internal_static_ru_chuprikov_search_database_datatypes_Posting_fieldAccessorTable;
      }
      
      // Construct using ru.chuprikov.search.database.datatypes.Datatypes.Posting.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPositionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        documentID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (positionsBuilder_ == null) {
          positions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          positionsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.chuprikov.search.database.datatypes.Datatypes.Posting.getDescriptor();
      }
      
      public ru.chuprikov.search.database.datatypes.Datatypes.Posting getDefaultInstanceForType() {
        return ru.chuprikov.search.database.datatypes.Datatypes.Posting.getDefaultInstance();
      }
      
      public ru.chuprikov.search.database.datatypes.Datatypes.Posting build() {
        ru.chuprikov.search.database.datatypes.Datatypes.Posting result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ru.chuprikov.search.database.datatypes.Datatypes.Posting buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ru.chuprikov.search.database.datatypes.Datatypes.Posting result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ru.chuprikov.search.database.datatypes.Datatypes.Posting buildPartial() {
        ru.chuprikov.search.database.datatypes.Datatypes.Posting result = new ru.chuprikov.search.database.datatypes.Datatypes.Posting(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.documentID_ = documentID_;
        if (positionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            positions_ = java.util.Collections.unmodifiableList(positions_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.positions_ = positions_;
        } else {
          result.positions_ = positionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.chuprikov.search.database.datatypes.Datatypes.Posting) {
          return mergeFrom((ru.chuprikov.search.database.datatypes.Datatypes.Posting)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ru.chuprikov.search.database.datatypes.Datatypes.Posting other) {
        if (other == ru.chuprikov.search.database.datatypes.Datatypes.Posting.getDefaultInstance()) return this;
        if (other.hasDocumentID()) {
          setDocumentID(other.getDocumentID());
        }
        if (positionsBuilder_ == null) {
          if (!other.positions_.isEmpty()) {
            if (positions_.isEmpty()) {
              positions_ = other.positions_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePositionsIsMutable();
              positions_.addAll(other.positions_);
            }
            onChanged();
          }
        } else {
          if (!other.positions_.isEmpty()) {
            if (positionsBuilder_.isEmpty()) {
              positionsBuilder_.dispose();
              positionsBuilder_ = null;
              positions_ = other.positions_;
              bitField0_ = (bitField0_ & ~0x00000002);
              positionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPositionsFieldBuilder() : null;
            } else {
              positionsBuilder_.addAllMessages(other.positions_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDocumentID()) {
          
          return false;
        }
        for (int i = 0; i < getPositionsCount(); i++) {
          if (!getPositions(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              documentID_ = input.readUInt64();
              break;
            }
            case 18: {
              ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder subBuilder = ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPositions(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 documentID = 1;
      private long documentID_ ;
      public boolean hasDocumentID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getDocumentID() {
        return documentID_;
      }
      public Builder setDocumentID(long value) {
        bitField0_ |= 0x00000001;
        documentID_ = value;
        onChanged();
        return this;
      }
      public Builder clearDocumentID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        documentID_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .ru.chuprikov.search.database.datatypes.Posting.Position positions = 2;
      private java.util.List<ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position> positions_ =
        java.util.Collections.emptyList();
      private void ensurePositionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          positions_ = new java.util.ArrayList<ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position>(positions_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position, ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder, ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionOrBuilder> positionsBuilder_;
      
      public java.util.List<ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position> getPositionsList() {
        if (positionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(positions_);
        } else {
          return positionsBuilder_.getMessageList();
        }
      }
      public int getPositionsCount() {
        if (positionsBuilder_ == null) {
          return positions_.size();
        } else {
          return positionsBuilder_.getCount();
        }
      }
      public ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position getPositions(int index) {
        if (positionsBuilder_ == null) {
          return positions_.get(index);
        } else {
          return positionsBuilder_.getMessage(index);
        }
      }
      public Builder setPositions(
          int index, ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position value) {
        if (positionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionsIsMutable();
          positions_.set(index, value);
          onChanged();
        } else {
          positionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPositions(
          int index, ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder builderForValue) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.set(index, builderForValue.build());
          onChanged();
        } else {
          positionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPositions(ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position value) {
        if (positionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionsIsMutable();
          positions_.add(value);
          onChanged();
        } else {
          positionsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPositions(
          int index, ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position value) {
        if (positionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionsIsMutable();
          positions_.add(index, value);
          onChanged();
        } else {
          positionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPositions(
          ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder builderForValue) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.add(builderForValue.build());
          onChanged();
        } else {
          positionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPositions(
          int index, ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder builderForValue) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.add(index, builderForValue.build());
          onChanged();
        } else {
          positionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPositions(
          java.lang.Iterable<? extends ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position> values) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          super.addAll(values, positions_);
          onChanged();
        } else {
          positionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPositions() {
        if (positionsBuilder_ == null) {
          positions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          positionsBuilder_.clear();
        }
        return this;
      }
      public Builder removePositions(int index) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.remove(index);
          onChanged();
        } else {
          positionsBuilder_.remove(index);
        }
        return this;
      }
      public ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder getPositionsBuilder(
          int index) {
        return getPositionsFieldBuilder().getBuilder(index);
      }
      public ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionOrBuilder getPositionsOrBuilder(
          int index) {
        if (positionsBuilder_ == null) {
          return positions_.get(index);  } else {
          return positionsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionOrBuilder> 
           getPositionsOrBuilderList() {
        if (positionsBuilder_ != null) {
          return positionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(positions_);
        }
      }
      public ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder addPositionsBuilder() {
        return getPositionsFieldBuilder().addBuilder(
            ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.getDefaultInstance());
      }
      public ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder addPositionsBuilder(
          int index) {
        return getPositionsFieldBuilder().addBuilder(
            index, ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.getDefaultInstance());
      }
      public java.util.List<ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder> 
           getPositionsBuilderList() {
        return getPositionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position, ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder, ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionOrBuilder> 
          getPositionsFieldBuilder() {
        if (positionsBuilder_ == null) {
          positionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position, ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder, ru.chuprikov.search.database.datatypes.Datatypes.Posting.PositionOrBuilder>(
                  positions_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          positions_ = null;
        }
        return positionsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ru.chuprikov.search.database.datatypes.Posting)
    }
    
    static {
      defaultInstance = new Posting(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ru.chuprikov.search.database.datatypes.Posting)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_chuprikov_search_database_datatypes_Posting_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_chuprikov_search_database_datatypes_Posting_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_chuprikov_search_database_datatypes_Posting_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_chuprikov_search_database_datatypes_Posting_Position_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Datatypes.proto\022&ru.chuprikov.search.d" +
      "atabase.datatypes\"\234\002\n\007Posting\022\022\n\ndocumen" +
      "tID\030\001 \002(\004\022K\n\tpositions\030\002 \003(\01328.ru.chupri" +
      "kov.search.database.datatypes.Posting.Po" +
      "sition\032e\n\010Position\022J\n\004type\030\001 \002(\0162<.ru.ch" +
      "uprikov.search.database.datatypes.Postin" +
      "g.PositionType\022\r\n\005index\030\002 \002(\r\"I\n\014Positio" +
      "nType\022\t\n\005TITLE\020\001\022\r\n\tCONDITION\020\002\022\016\n\nINPUT" +
      "_SPEC\020\003\022\017\n\013OUTPUT_SPEC\020\004B\013B\tDatatypes"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ru_chuprikov_search_database_datatypes_Posting_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ru_chuprikov_search_database_datatypes_Posting_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ru_chuprikov_search_database_datatypes_Posting_descriptor,
              new java.lang.String[] { "DocumentID", "Positions", },
              ru.chuprikov.search.database.datatypes.Datatypes.Posting.class,
              ru.chuprikov.search.database.datatypes.Datatypes.Posting.Builder.class);
          internal_static_ru_chuprikov_search_database_datatypes_Posting_Position_descriptor =
            internal_static_ru_chuprikov_search_database_datatypes_Posting_descriptor.getNestedTypes().get(0);
          internal_static_ru_chuprikov_search_database_datatypes_Posting_Position_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ru_chuprikov_search_database_datatypes_Posting_Position_descriptor,
              new java.lang.String[] { "Type", "Index", },
              ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.class,
              ru.chuprikov.search.database.datatypes.Datatypes.Posting.Position.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
